### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 316: ordinal not in range(128)

### ISSUE THREAD

**Issue by xumical** [jongmartinez/Wilson_XSS#1]
1.  python3 wilsonxss.py -u http://testphp.vulnweb.com
2. Profit.: 
[23:17:35] [INFO] Starting Wilson_XSS...
Traceback (most recent call last):
  File "wilsonxss.py", line 85, in <module>
    start()
  File "wilsonxss.py", line 62, in start
    core.main(getopt.u,getopt.proxy,getopt.user_agent,check(getopt),populate_list(),getopt.method)
  File "wilsonxss.py", line 20, in populate_list
    for line in r.readlines():
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 316: ordinal not in range(128)
root@root:~/Wilson_XSS# UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 316: ordinal not in range(128)

![download](https://user-images.githubusercontent.com/44411392/58300590-0a21d080-7d98-11e9-92b2-6beaf5662954.png)

**Comment by xumical** [comment]
Solved with installing python 3.7, but throws another error running the same command. -  Traceback (most recent call last):
  File "wilsonxss.py", line 85, in <module>
    start()
  File "wilsonxss.py", line 62, in start
    core.main(getopt.u,getopt.proxy,getopt.user_agent,check(getopt),populate_list(),getopt.method)
  File "/root/Wilson_XSS/lib/core.py", line 191, in main
    self.post_method()
  File "/root/Wilson_XSS/lib/core.py", line 76, in post_method
    log_wilson.write("\nPayload used: {x}", x=str(xss_payload))
TypeError: write() takes no keyword arguments

**Comment by jongmartinez** [comment]
Thank you! Just pushed the fix

**Comment by xumical** [comment]
@jongmartinez Updating throws a new error for me. -  python3.7 wilsonxss.py -u http://testphp.vulnweb.com
Traceback (most recent call last):
  File "wilsonxss.py", line 10, in <module>
    from lib.core import *
  File "/root/Wilson_XSS/lib/core.py", line 76
    log_wilson.write("\nPayload used: "+ x=str(xss_payload))
                    ^
SyntaxError: keyword can't be an expression

**Comment by jongmartinez** [comment]
Just pushed again, i think it should be working now

**Comment by xumical** [comment]
Fixed. :-)
